
macro(check_param name msg)
if (NOT DEFINED ${name})
  set(${name} $ENV{${name}})
endif()
if (NOT DEFINED ${name})
  message(FATAL_ERROR "Set ${msg} using ${name} variable")
endif()
endmacro()


macro(set_param name doc)
if (NOT DEFINED ${name})
  set(${name} $ENV{${name}})
endif()
if (NOT DEFINED ${name} AND ${ARGC} GREATER 2)
  set(${name} ${ARGN})
endif()
endmacro()


macro(start branch)
message("\n==== START ====\n")
if(branch MATCHES "master.*")
  ctest_start("Continuous")
else()
  ctest_start("Experimental")
endif()
message("\n===============\n")
endmacro()

macro(step msg)
message("\n---- ${msg}\n")
endmacro()

macro(fail msg)
if(NOT DEFINED SUBMIT OR SUBMIT)
  step("submitting result to cdash")
  ctest_submit()
endif()
message(FATAL_ERROR ${msg})
endmacro()

macro(done)
if(NOT DEFINED SUBMIT OR SUBMIT)
  step("submitting result to cdash")
  ctest_submit()
endif()
message("\n==== DONE ====\n")
endmacro()
